package com.spring.boot.util.factory.log.helpers;

import com.spring.boot.util.factory.log.Log;
import org.slf4j.Logger;
import org.springframework.lang.Nullable;

/**
 * Implement the methods of Log
 *
 * @author Zhengmin Yu
 * @see LogContent
 * @see com.spring.boot.util.factory.LogFactory
 */
public class LogContent implements Log {

    /**
     * Generated by <code>getLogger(Class<?> clazz)</code> in <code>slf4j</code>
     */
    Logger logger;

    public LogContent(@Nullable Logger logger) {
        this.logger = logger;
    }

    @Override
    public void trace(String message, Object... content) {
        if (logger.isTraceEnabled()) {
            logger.trace(message, content);
        } else {
            debug("TRACE level logging is not supported, message = {}", message);
        }
    }

    @Override
    public void debug(String message, Object... content) {
        if (logger.isDebugEnabled()) {
            logger.debug(message, content);
        } else {
            info("DEBUG level logging is not supported, message = [{}]", message);
        }
    }

    @Override
    public void info(String message, Object... content) {
        if (logger.isInfoEnabled()) {
            logger.info(message, content);
        } else {
            warn("INFO level logging is not supported, message = [{}]", message);
        }
    }

    @Override
    public void warn(String message, Object... content) {
        if (logger.isWarnEnabled()) {
            logger.warn(message, content);
        } else {
            error("WARN level logging is not supported, message = [{}]", message);
        }
    }

    @Override
    public void error(String message, Object... content) {
        if (logger.isErrorEnabled()) {
            logger.error(message, content);
        }
    }

    @Override
    public void error(String message, Exception e, Object... content) {
        if (logger.isErrorEnabled()) {
            logger.error(message + " Exception: {}", content, e);
        }
    }

}
